config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }  

  resources :users
  resources :price_notifications
end

app/models/price_notification.rb
class PriceNotification < ActiveRecord::Base
  include Common::Uuid

  extend FriendlyId

  friendly_id :uuid

  belongs_to :user

  symbolize :direction
  symbolize :exchange

  validates :exchange, presence: true
  validates :price, presence: true
  validates :direction, presence: true, inclusion: {in: [:below, :above]}

  def human_exchange_name
    self.class.exchange_human_names[exchange]
  end

  def self.exchange_human_names
    {
      bitstamp: 'Bitstamp.com',
      coinbase: 'Coinbase.com'
    }
  end
  
  def self.send_alerts!
    self.exchange_human_names.keys.map{ |exch| "::Exchange::#{exch.to_s.camelize}".constantize }.each do |exchange_klass|
      exchange = exchange_klass.new    
      price = exchange.current_price

      matching_notifications = where(
        "exchange = :exchange AND "\
        "((direction = :below AND price >= :price) OR "\
        "(direction = :above AND price <= :price)) AND "\
        "(last_notification_time IS NULL OR last_notification_time < :renotify_threshold)",
        exchange: exchange.name,
        below: :below,
        above: :above,
        price: exchange.current_price,
        renotify_threshold: 6.hours.ago
      )

      matching_notifications.each do |price_notificaton|
        PriceNotificationMailer.notification(price_notificaton.id, exchange.current_price).deliver
        price_notificaton.update!(last_notification_time: Time.now)
      end
    end
  end
end

app/controllers/price_notifications_controller.rb
class PriceNotificationsController < ApplicationController
  before_filter :require_login

  before_filter :find_and_authorize_price_notification, only: [:edit, :update, :destroy]

  before_filter :add_breadcrumbs, only: [:edit]

  handles_sortable_columns

  def index
    if sort_param.blank?
      flash.keep
      redirect_to(price_notifications_path(sort: '-created_at')) and return
    end

    @price_notifications = current_user.price_notifications.order(sort_order).page(page_param)
  end
  
  def new
    @price_notification = PriceNotification.new(price_notification_params)
  end

  def create
    @price_notification = current_user.price_notifications.new(price_notification_params)

    if @price_notification.save
      redirect_to price_notifications_path, flash: {notice: "Your notification was successfully added"}
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @price_notification.update(price_notification_params)
      redirect_to edit_price_notification_path(@price_notification), flash: {notice: 'Price notification successfully updated'}
    else
      render :edit
    end
  end

  def destroy
    @price_notification.destroy

    redirect_to price_notifications_path, flash: {alert: 'Your notification was successfully deleted'}
  end

  private

  def price_notification_params
    params.permit(price_notification: [:exchange, :price, :direction])[:price_notification]
  end

  def sort_order
    sortable_column_order || 'created_at DESC'
  end

  def find_and_authorize_price_notification
    @price_notification = PriceNotification.friendly.find(id_param)
    authorize! :modify, @price_notification
  end

  def add_breadcrumbs
    add_breadcrumb('Price Notifications', price_notifications_path)
    add_breadcrumb('Edit', edit_price_notification_path(@price_notification))
  end
end

app/views/price_notifications/_form.haml
.row
  .col-md-4.col-md-offset-4.col-xs-10.col-xs-offset-1
    = semantic_form_for @price_notification, html: {id: 'price-notification-form'} do |f|  
      #price-notification.panel.panel-default
        - verb = @price_notification.new_record? ? 'Create' : 'Update'
        .panel-heading
          %h3.panel-title= "#{verb} Price Notification"
        .panel-body
          = f.inputs do
            = f.input :direction, as: :select, label: 'Notify me when', collection: {'Price goes below' => :below, 'Price goes above' => :above}, include_blank: false

            = f.input :price, as: :string, prepend_content: content_tag(:span, '$', class: 'input-group-addon')

            = f.input :exchange, as: :select, label: 'On the Exchange', collection: {'Bitstamp.com' => :bitstamp, 'Coinbase.com' => :coinbase}, include_blank: false

          = f.actions do
            - if !@price_notification.new_record?
              = link_to nil, href: price_notification_path(@price_notification), class: 'delete-link text-danger pull-left', data: {method: :delete, confirm: 'Are you sure you want to delete this notification?'} do
                %i.glyphicon.glyphicon-trash
                Delete Notification

            = f.action :submit, label: 'Save Notification', button_html: {data: {disable_with: 'Saving...'}, class: 'btn btn-default pull-right'}

app/views/price_notifications/edit.haml
= render 'form'

app/views/price_notifications/index.haml
-# cache [sort_param, page_param, @price_notifications.maximum(:updated_at)] do
#price-notifications-index
  .row
    .col-xs-8.col-xs-offset-2
      .row
        .col-xs-12
          = link_to 'Add Notification', new_price_notification_path, class: 'btn btn-primary pull-right'

      .breaker.md

      %table#price-notifications-table.table.clickable-rows
        %thead
          %tr
            %th= sortable_column 'Above/Below', column: :direction
            %th= sortable_column 'Price'
            %th= sortable_column 'Exchange'
            %th= sortable_column 'Added On', column: :created_at

        %tbody
          - if @price_notifications.empty?
            %tr.empty
              %td{colspan: '4'}
                You have not yet added any price notifications

          - @price_notifications.each do |price_notification|
            %tr{data: {url: edit_price_notification_path(price_notification)}}
              %td= price_notification.direction == :above ? 'Above' : 'Below'
              %td= number_to_currency price_notification.price
              %td= price_notification.human_exchange_name
              %td= price_notification.created_at.to_s(:slashes)

      .pagination-wrap
        = paginate @price_notifications

app/views/price_notifications/new.haml
= render 'form'