config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }  

  resources :users
  resources :price_notifications
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title BTCPing.Me
    = render partial: "common/fonts"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar
      .navbar-header
        .row-fluid
          - url = user_signed_in? ? price_notifications_path : root_path
          = link_to nil, href: url, class: "navbar-brand", id: "logo" do
            %i.fa.fa-bitcoin
            .logo-rest
              TCPing.me
      
      %ul#account-dropdown.nav.navbar-nav.navbar-right
        %li.dropdown
          %a#my-account.dropdown-toggle{data: {toggle: "dropdown"}}
            My Account
            %i.fa.fa-chevron-down

          %ul.dropdown-menu
            - if user_signed_in?  
              %li
                = link_to "Home", price_notifications_path

              %li
                = link_to "Manage Account", edit_user_path(current_user)

              %li
                = link_to "Sign Out", destroy_user_session_path, data: {method: :delete}
            - else
              %li
                =link_to "Sign In", new_user_session_path

    #main-container.container
      = alerts
      
      - if  @breadcrumbs.try(:any?)
        .row
          .col-xs-8.col-xs-offset-2
            = render_breadcrumbs builder: ::BootstrapBreadcrumbsBuilder

      = yield

app/views/layouts/email.haml
!!!
%html
  %head
    %link{type: 'text/css', rel: 'stylesheet', href: '/assets/email.css'}
  
  %body
    = yield